# Generated by Django 5.1.15 on 2026-06-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_site_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='platform',
            field=models.CharField(choices=[('woocommerce', 'WooCommerce'), ('sapo', 'Sapo Web')], db_index=True, default='woocommerce', max_length=20),
        ),
    ]
