# Generated by Django 5.1.15 on 2026-06-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_site_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='sapo_store_host',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
