# Generated by Django 5.1.15 on 2026-06-05 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_hosting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Khỏe mạnh'), ('warning', 'Cảnh báo'), ('critical', 'Lỗi nghiêm trọng')], db_index=True, max_length=20)),
                ('check_type', models.CharField(choices=[('periodic', 'Kiểm tra định kỳ'), ('manual', 'Kiểm tra thủ công')], default='manual', max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='sites.site')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['status', 'checked_at'], name='monitoring__status_636b2b_idx'), models.Index(fields=['site', 'checked_at'], name='monitoring__site_id_89358a_idx')],
            },
        ),
    ]
