# Generated by Django 5.1.15 on 2026-06-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_sitenote_sitenoteimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('error', 'Error')], db_index=True, max_length=20)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('deleted_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', 'created_at'], name='sync_synclo_operati_c2a68a_idx')],
            },
        ),
    ]
