# Generated by Django 5.1.15 on 2026-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='run_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
