# Generated by Django 5.1.15 on 2026-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
