# Generated by Django 5.1.15 on 2026-06-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_hosting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_order_id', models.BigIntegerField()),
                ('number', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(db_index=True, max_length=30)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('shipping_address', models.TextField(blank=True)),
                ('customer_note', models.TextField(blank=True)),
                ('line_items', models.JSONField(default=list)),
                ('date_created_woo', models.DateTimeField(db_index=True)),
                ('forwarded', models.BooleanField(db_index=True, default=False)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sites.site')),
            ],
            options={
                'ordering': ['-date_created_woo'],
                'indexes': [models.Index(fields=['site', 'date_created_woo'], name='orders_orde_site_id_38a0b8_idx'), models.Index(fields=['status', 'date_created_woo'], name='orders_orde_status_985039_idx'), models.Index(fields=['forwarded', 'date_created_woo'], name='orders_orde_forward_162a34_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'woo_order_id'), name='order_unique_per_site')],
            },
        ),
    ]
