# Generated by Django 5.1.15 on 2026-06-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('sites', '0003_hosting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_modified_woo',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['site', 'status', 'date_modified_woo'], name='orders_orde_site_id_2372c7_idx'),
        ),
    ]
