# Generated by Django 5.1.15 on 2026-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_backfill_forwarded_completed'),
        ('sites', '0005_site_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='classification',
            field=models.CharField(choices=[('genuine', 'Hợp lệ'), ('suspicious', 'Nghi ngờ'), ('spam', 'Spam/Bot')], db_index=True, default='genuine', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['classification', 'date_created_woo'], name='orders_orde_classif_cb2e15_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_phone', 'date_created_woo'], name='orders_orde_custome_617ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email', 'date_created_woo'], name='orders_orde_custome_c59e4b_idx'),
        ),
    ]
