# Generated by Django 5.1.15 on 2026-07-04 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created_woo'], 'permissions': [('sync_order', 'Có thể đồng bộ đơn hàng từ website'), ('forward_order', 'Có thể chuyển đơn sang marketing'), ('email_order', 'Có thể gửi email đơn hàng')]},
        ),
    ]
