# Generated by Django 5.1.15 on 2026-06-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_sitenote_sitenoteimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='simple', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('pending', 'Pending'), ('private', 'Private')], default='draft', max_length=20)),
                ('stock_status', models.CharField(choices=[('instock', 'In stock'), ('outofstock', 'Out of stock'), ('onbackorder', 'On backorder')], default='instock', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('images', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_product_id', models.BigIntegerField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='catalog.masterproduct')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('master', 'site'), name='mapping_unique_master_site'), models.UniqueConstraint(fields=('site', 'woo_product_id'), name='mapping_unique_site_woo')],
            },
        ),
    ]
