# Generated by Django 5.1.15 on 2026-06-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sites', '0004_sitenote_sitenoteimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255)),
                ('parent_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='attributes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='grouped_skus',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='variations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('grouped', 'Grouped'), ('external', 'External/Affiliate'), ('variable', 'Variable')], default='simple', max_length=20),
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_category_id', models.BigIntegerField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='catalog.category')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'site'), name='catmap_unique_category_site'), models.UniqueConstraint(fields=('site', 'woo_category_id'), name='catmap_unique_site_woo')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_sku', models.CharField(db_index=True, max_length=120)),
                ('woo_variation_id', models.BigIntegerField()),
                ('woo_parent_id', models.BigIntegerField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_mappings', to='catalog.masterproduct')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_mappings', to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('master', 'site', 'variation_sku'), name='varmap_unique_master_site_sku'), models.UniqueConstraint(fields=('site', 'woo_variation_id'), name='varmap_unique_site_woo')],
            },
        ),
    ]
