# Generated by Django 5.1.15 on 2026-06-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymapping',
            name='woo_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
