# Generated by Django 5.1.15 on 2026-07-01 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sitemediaasset'),
        ('sites', '0008_site_sapo_store_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdoptionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiguous', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_scans', to='catalog.masterproduct')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_scans', to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('master', 'site'), name='adoptscan_unique_master_site')],
            },
        ),
    ]
