# Generated by Django 5.1.15 on 2026-07-04 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productadoptionscan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': [('pull_category', 'Có thể đồng bộ danh mục từ website')], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='masterproduct',
            options={'ordering': ['-updated_at'], 'permissions': [('push_masterproduct', 'Có thể đẩy sản phẩm sang website')]},
        ),
    ]
