# Generated by Django 5.1.15 on 2026-06-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_enc', models.BinaryField(blank=True, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('from_name', models.CharField(blank=True, default='Solar Hub', max_length=255)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('digest_enabled', models.BooleanField(default=True)),
                ('last_digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Mail SMTP',
                'verbose_name_plural': 'Cấu hình Mail SMTP',
            },
        ),
    ]
