# Generated by Django 5.1.15 on 2026-07-04 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_mailsettings_digest_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsettings',
            options={'permissions': [('test_mailsettings', 'Có thể gửi email thử')], 'verbose_name': 'Cấu hình Mail SMTP', 'verbose_name_plural': 'Cấu hình Mail SMTP'},
        ),
    ]
