# Generated by Django 5.1.15 on 2026-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_mailsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='product_sync_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='product_sync_report_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
