# Generated by Django 5.1.15 on 2026-07-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0008_site_sapo_store_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('whois_status', models.CharField(choices=[('pending', 'Đang kiểm tra'), ('ok', 'Thành công'), ('partial', 'Thiếu một phần'), ('error', 'Lỗi'), ('unsupported', 'Chưa hỗ trợ'), ('skipped', 'Bỏ qua')], default='pending', max_length=20)),
                ('whois_registrar', models.CharField(blank=True, max_length=255)),
                ('whois_created_at', models.DateTimeField(blank=True, null=True)),
                ('whois_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('whois_source', models.CharField(blank=True, max_length=20)),
                ('whois_raw', models.JSONField(blank=True, default=dict)),
                ('whois_checked_at', models.DateTimeField(blank=True, null=True)),
                ('dns_status', models.CharField(choices=[('pending', 'Đang kiểm tra'), ('ok', 'Thành công'), ('partial', 'Thiếu một phần'), ('error', 'Lỗi'), ('unsupported', 'Chưa hỗ trợ'), ('skipped', 'Bỏ qua')], default='pending', max_length=20)),
                ('dns_records', models.JSONField(blank=True, default=dict)),
                ('dns_checked_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_status', models.CharField(choices=[('pending', 'Đang kiểm tra'), ('ok', 'Thành công'), ('partial', 'Thiếu một phần'), ('error', 'Lỗi'), ('unsupported', 'Chưa hỗ trợ'), ('skipped', 'Bỏ qua')], default='pending', max_length=20)),
                ('ssl_issuer', models.CharField(blank=True, max_length=255)),
                ('ssl_subject', models.CharField(blank=True, max_length=255)),
                ('ssl_not_before', models.DateTimeField(blank=True, null=True)),
                ('ssl_not_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ssl_checked_at', models.DateTimeField(blank=True, null=True)),
                ('blacklist_status', models.CharField(choices=[('pending', 'Đang kiểm tra'), ('ok', 'Thành công'), ('partial', 'Thiếu một phần'), ('error', 'Lỗi'), ('unsupported', 'Chưa hỗ trợ'), ('skipped', 'Bỏ qua')], default='pending', max_length=20)),
                ('blacklist_verdict', models.CharField(choices=[('clean', 'Sạch'), ('listed', 'Bị liệt kê'), ('unknown', 'Không xác định')], default='unknown', max_length=10)),
                ('blacklist_results', models.JSONField(blank=True, default=list)),
                ('blacklist_checked_at', models.DateTimeField(blank=True, null=True)),
                ('gindex_status', models.CharField(choices=[('pending', 'Đang kiểm tra'), ('ok', 'Thành công'), ('partial', 'Thiếu một phần'), ('error', 'Lỗi'), ('unsupported', 'Chưa hỗ trợ'), ('skipped', 'Bỏ qua')], default='skipped', max_length=20)),
                ('gindex_indexed', models.BooleanField(blank=True, null=True)),
                ('gindex_total_results', models.BigIntegerField(blank=True, null=True)),
                ('gindex_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_info', to='sites.site')),
            ],
            options={
                'ordering': ['domain', 'id'],
            },
        ),
    ]
