# Generated by Django 5.1.15 on 2026-07-04 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domaininfo',
            options={'ordering': ['domain', 'id'], 'permissions': [('refresh_domaininfo', 'Có thể kiểm tra lại thông tin tên miền')]},
        ),
    ]
